name: gradle test

on:
  pull_request:
    paths:
      - '**.java'
      - '**.properties'
      - '*.gradle'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: corretto
      - run: ./gradlew test
